version: "3.7"

services:
  php:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: ${PHP_CONTAINER_BUILD_TARGET}
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8010:80"
